import { OrganizationType } from './types';

/* eslint-disable no-useless-escape */
//大小寫英文+數字，長度10-128
export const PASSWORD_REGEX =
  /^.*(?=.{10,128})(?!.*\s)(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\!\@\#\$\%\^\&\*\(\)\-\=\¡\£\_\+\`\~\.\,\<\>\/\?\;\:\'\"\\\|\[\]\{\}]).*$/;

export const AGE_DATA = [
  { namespace: 'Above_13', key: 'above_thirteen', under: false },
  { namespace: 'Under_13', key: 'under_thirteen', under: true },
];
export const TYPE_DATA = [
  { namespace: OrganizationType.Distributor, key: OrganizationType.Distributor },
  {
    namespace: OrganizationType.Reseller_System_Integrator,
    key: OrganizationType.Reseller_System_Integrator,
  },
  { namespace: OrganizationType.School, key: OrganizationType.School },
  { namespace: OrganizationType.University, key: OrganizationType.University },
  { namespace: OrganizationType.Enterprise, key: OrganizationType.Enterprise },
  { namespace: OrganizationType.Individual, key: OrganizationType.Individual },
  { namespace: OrganizationType.Others, key: OrganizationType.Others },
];

export const OPTOMA_REGION_DATA = {
  EMEA: [
    'AL',
    'AM',
    'AT',
    'AZ',
    'BH',
    'BY',
    'BE',
    'BJ',
    'BA',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK',
    'EG',
    'EE',
    'FI',
    'FR',
    'PF',
    'GE',
    'DE',
    'GR',
    'HU',
    'IS',
    'IE',
    'IL',
    'IT',
    'JO',
    'KZ',
    'KW',
    'LV',
    'LB',
    'LR',
    'LT',
    'LU',
    'MK',
    'MT',
    'MQ',
    'MU',
    'MD',
    'MA',
    'NG',
    'NO',
    'OM',
    'PL',
    'PT',
    'QA',
    'RE',
    'RO',
    'RU',
    'RW',
    'SA',
    'RS',
    'SK',
    'SI',
    'ZA',
    'ES',
    'SE',
    'CH',
    'NL',
    'TR',
    'UA',
    'AE',
    'GB',
    'UZ',
  ],
  Americas: ['BS', 'BR', 'CA', 'CL', 'PE', 'PR', 'US'],
  AsiaOceania: [
    'AU',
    'BD',
    'FJ',
    'IN',
    'JP',
    'MY',
    'MV',
    'MN',
    'NP',
    'NZ',
    'PK',
    'PH',
    'SG',
    'KR',
    'LK',
    'TW',
    'TH',
    'VN',
    'HK',
  ],
  China: ['CN'],
};
